### ISSUE TITLE
Up to date with the latest?

### ISSUE THREAD

**Issue by charlesrwest** [spookyboo/HLMSEditor#24]
I'm building the editor using cmake on Ubuntu Linux 16.04.  

I ran into a problem with Ogre including a header that is windows specific (despite Ogre itself building fine) and suppressed it by putting 

    add_definitions(-D_OgreAssert_H_)

in the Unix portion of the cmake file.  I then got an error specifying that certain features in the code required the C++11 standard and that it had not been enabled.  I fixed that by specifying the version of C++ by adding 

set (CMAKE_CXX_STANDARD 11)

to the top of the cmake file.  However, I then ran into a problem where a function call in the code appears to not be in sync with the Ogre library:

`[ 65%] Building CXX object CMakeFiles/HLMSEditor.dir/framework/src/asset_propertywidget_texture.cpp.o
CMakeFiles/HLMSEditor.dir/build.make:1022: recipe for target 'CMakeFiles/HLMSEditor.dir/source/src/hlms_utils_manager.cpp.o' failed
make[2]: *** [CMakeFiles/HLMSEditor.dir/source/src/hlms_utils_manager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/charlesrwest/cpp/libraries/HLMSEditor/source/src/mainwindow.cpp: In member function ‘void MainWindow::saveDatablock(bool)’:
/home/charlesrwest/cpp/libraries/HLMSEditor/source/src/mainwindow.cpp:1050:52: error: no matching function for call to ‘Ogre::HlmsManager::saveMaterial(Ogre::HlmsDatablock*&, Ogre::String&)’
         hlmsManager->saveMaterial (datablock, fname);
                                                    ^
In file included from /usr/local/include/OGRE/OgreHardwareBufferManager.h:39:0,
                 from /usr/local/include/OGRE/OgreItem.h:37,
                 from /home/charlesrwest/cpp/libraries/HLMSEditor/framework/header/ogre3_widget.h:32,
                 from /home/charlesrwest/cpp/libraries/HLMSEditor/source/header/constants.h:29,
                 from /home/charlesrwest/cpp/libraries/HLMSEditor/source/src/mainwindow.cpp:22:
/usr/local/include/OGRE/OgreHlmsManager.h:303:14: note: candidate: void Ogre::HlmsManager::saveMaterial(const Ogre::HlmsDatablock*, const String&, Ogre::HlmsJsonListener*, const String&)
         void saveMaterial( const HlmsDatablock *datablock, const String &filena
              ^
/usr/local/include/OGRE/OgreHlmsManager.h:303:14: note:   candidate expects 4 arguments, 2 provided`

I have compiled and installed the latest of the v2-1 branch for both debug and release.  If I may ask, what commit should I be using with the editor right now?

Thanks!

**Comment by spookyboo** [comment]
Hi,

 

I am using the commit of Jan 23, 2018

e6c85a8ee58f

 

Regards,

Henry

**Comment by spookyboo** [comment]
The HLMS editor is updated with Ogre commit 8863ddf20ded of April 2.
