### ISSUE TITLE
Crash when assigning pbs to Mesh

### ISSUE THREAD

**Issue by mazataza** [spookyboo/HLMSEditor#3]
I was playing with your Editor to create some Materials. 
i have downloaded the sources and used the binaries you provided.
when creating new pbs and assign it to a Mesh the tool crash.

**Comment by spookyboo** [comment]
I don't have enough info. It should work.
Are all the directories properly created? You should have a bin, common, doc, examples, import and temp directory. If so, check whether the application has enough access right to these directories (if not, the application could crash).

**Comment by spookyboo** [comment]
Better not to use the binary included in the source btw. Better use this one: https://github.com/spookyboo/HLMSEditor/releases/download/0.8/setup.exe

**Comment by mazataza** [comment]
yes you are correct using the version from setup.exe it works very good.
thank for quick anwser

**Comment by spookyboo** [comment]
I'll close it then
